# Generated by Django 5.0.6 on 2024-05-10 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 20, 9, 49, 555514)),
            preserve_default=False,
        ),
    ]
