# Generated by Django 5.0.6 on 2024-05-10 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 20, 57, 21, 545777)),
            preserve_default=False,
        ),
    ]
